name: React CI

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node - version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
